// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJaRZSMHA3rlGVDswSXGsij_C3AJXEAM',
    appId: '1:356746976993:web:210237b2f54386fd5da1a0',
    messagingSenderId: '356746976993',
    projectId: 'tharwatsam-199a5',
    authDomain: 'tharwatsam-199a5.firebaseapp.com',
    storageBucket: 'tharwatsam-199a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1dY4L18Rt99CnKJb7pfq9ZR_KdvrlGI',
    appId: '1:356746976993:android:3f5c5cdaedec43b55da1a0',
    messagingSenderId: '356746976993',
    projectId: 'tharwatsam-199a5',
    storageBucket: 'tharwatsam-199a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSHx8xzoRX23GZXW7LTTPeWj_AqcKQIc',
    appId: '1:356746976993:ios:b04d8338acfe65145da1a0',
    messagingSenderId: '356746976993',
    projectId: 'tharwatsam-199a5',
    storageBucket: 'tharwatsam-199a5.firebasestorage.app',
    androidClientId: '356746976993-7u1e611huui1l4cpctdigkqfvsjkt1vn.apps.googleusercontent.com',
    iosClientId: '356746976993-6n57lp8eg82kgcv06c35jgljf6iuku9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniChatAppMentorAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSHx8xzoRX23GZXW7LTTPeWj_AqcKQIc',
    appId: '1:356746976993:ios:b04d8338acfe65145da1a0',
    messagingSenderId: '356746976993',
    projectId: 'tharwatsam-199a5',
    storageBucket: 'tharwatsam-199a5.firebasestorage.app',
    androidClientId: '356746976993-7u1e611huui1l4cpctdigkqfvsjkt1vn.apps.googleusercontent.com',
    iosClientId: '356746976993-6n57lp8eg82kgcv06c35jgljf6iuku9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniChatAppMentorAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJaRZSMHA3rlGVDswSXGsij_C3AJXEAM',
    appId: '1:356746976993:web:81a2d1db095ee83e5da1a0',
    messagingSenderId: '356746976993',
    projectId: 'tharwatsam-199a5',
    authDomain: 'tharwatsam-199a5.firebaseapp.com',
    storageBucket: 'tharwatsam-199a5.firebasestorage.app',
  );
}
